### ISSUE TITLE
members command unpacks 'Addr' field to something unintelligible 

### ISSUE THREAD

**Issue by maratoid** [ranjib/serfx#16]
Serfx.connect(host: 'some ip', port: 'some port', authkey: 'some auth key') do |conn|
        puts conn.members.body['Members']
    end

will result in something like:

    {
               "Addr" => "\xD8\a\x90\u001D",
        "DelegateCur" => 4,
        "DelegateMax" => 4,
        "DelegateMin" => 2,
               "Name" => "some member",
               "Port" => 7949,
        "ProtocolCur" => 2,
        "ProtocolMax" => 2,
        "ProtocolMin" => 1,
             "Status" => "alive",
               ...
    }

Note the "Addr" field.

**Comment by ranjib** [comment]
@maratoid i have updated the readme. https://github.com/ranjib/serfx#note
